events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11;

    server {
        listen 8081;
        location / {
            proxy_pass http://session-service:8081;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 8087;
        location / {
            proxy_pass http://gateway-service:8087;
            proxy_set_header Host $host;
        }
    }
}
